# 7a) Basic Statistics

In [2]:
from scipy.stats import ttest_ind_from_stats
#use pandas to load csv file
import pandas as pandas
#use numpy to calculate stuff
import numpy as np

In [3]:
#load data
redwinedata = pandas.read_csv('data/winequality-red.csv', sep =';')
whitewinedata = pandas.read_csv('data/winequality-white.csv', sep =';')

### Redwine Data

In [4]:
redwinedata.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

### Whitewine Data

In [5]:
whitewinedata.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000
mean,6.854788,0.278241,0.334192,6.391415,0.045772,35.308085,138.360657,0.994027,3.188267,0.489847,10.514267,5.877909
std,0.843868,0.100795,0.121020,5.072058,0.021848,17.007137,42.498065,0.002991,0.151001,0.114126,1.230621,0.885639
min,3.800000,0.080000,0.000000,0.600000,0.009000,2.000000,9.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.300000,0.210000,0.270000,1.700000,0.036000,23.000000,108.000000,0.991723,3.090000,0.410000,9.500000,5.000000
50%,6.800000,0.260000,0.320000,5.200000,0.043000,34.000000,134.000000,0.993740,3.180000,0.470000,10.400000,6.000000
75%,7.300000,0.320000,0.390000,9.900000,0.050000,46.000000,167.000000,0.996100,3.280000,0.550000,11.400000,6.000000
max,14.200000,1.100000,1.660000,65.800000,0.346000,289.000000,440.000000,1.038980,3.820000,1.080000,14.200000,9.000000

Based on the data above there are several features which distinguish redwine from whitewine e.g. residual sugar seems to be significantly different (white wine is indeed sweeter) as well as volatile acidity and sulfur dioxide values. 
I assume that a clustering algorithm is able to pick up those differences, maybe dropping some features would be of help.

In [22]:
redwinestats = redwinedata.describe()
whitewinestats = whitewinedata.describe()

### T-Tests
Because it will also be useful for 7.c) we calculate some T-Test. 
The results show that all of the differences in the features are significant.
In order of descending absolute t-values, the significance is:
1. total sulfur dioxide 
2. volatile acidity
3. chlorides
4. sulvates
5. fixed acidity
6. free sulfur dioxide
7. density
8. residual sugar
9. pH
10. citric acid
11. quality
12. alcohol

In [29]:
for featureNr in range(0, redwinestats.shape[1]):
    print(list(redwinestats)[featureNr] + ": ")
    print(
    ttest_ind_from_stats(
        mean1=redwinestats.iloc[1,featureNr], std1=redwinestats.iloc[2,featureNr], nobs1=redwinestats.iloc[0,featureNr], 
        mean2=whitewinestats.iloc[1,featureNr], std2=whitewinestats.iloc[2,featureNr], nobs2=whitewinestats.iloc[0,featureNr]
    )
    )
    print()

fixed acidity:
Ttest_indResult(statistic=44.90556823034994, pvalue=0.0)

volatile acidity:
Ttest_indResult(statistic=69.49328807560799, pvalue=0.0)

citric acid:
Ttest_indResult(statistic=-15.374954114169297, pvalue=2.003735701834766e-52)

residual sugar:
Ttest_indResult(statistic=-29.996104565841236, pvalue=2.9593541527042885e-185)

chlorides:
Ttest_indResult(statistic=48.12306603007984, pvalue=0.0)

free sulfur dioxide:
Ttest_indResult(statistic=-43.10610584206572, pvalue=0.0)

total sulfur dioxide:
Ttest_indResult(statistic=-79.07462032921993, pvalue=0.0)

density:
Ttest_indResult(statistic=34.20022289522647, pvalue=7.31960462516311e-236)

pH:
Ttest_indResult(statistic=28.09002558145368, pvalue=5.923307967110629e-164)

sulphates:
Ttest_indResult(statistic=44.96340217575478, pvalue=0.0)

alcohol:
Ttest_indResult(statistic=-2.658512898748449, pvalue=0.007867873993300209)

quality:
Ttest_indResult(statistic=-9.685649554187581, pvalue=4.888069044207019e-22)